export const schemaCatalog = {
  relational: {
    dialect: "sqlite",
    tables: {
      sales_order_headers: {
        description: "Sales order header records",
        primaryKey: ["salesOrder"],
        columns: [
          "salesOrder",
          "salesOrderType",
          "salesOrganization",
          "distributionChannel",
          "organizationDivision",
          "soldToParty",
          "creationDate",
          "totalNetAmount",
          "overallDeliveryStatus",
          "overallOrdReltdBillgStatus",
          "transactionCurrency",
          "requestedDeliveryDate",
          "customerPaymentTerms",
        ],
      },
      sales_order_items: {
        description: "Sales order item lines",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "salesOrder",
          "salesOrderItem",
          "material",
          "requestedQuantity",
          "requestedQuantityUnit",
          "netAmount",
          "transactionCurrency",
          "productionPlant",
          "storageLocation",
        ],
      },
      sales_order_schedule_lines: {
        description: "Schedule lines for sales order items",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "salesOrder",
          "salesOrderItem",
          "scheduleLine",
          "confirmedDeliveryDate",
          "orderQuantityUnit",
          "confdOrderQtyByMatlAvailCheck",
        ],
      },
      outbound_delivery_headers: {
        description: "Outbound delivery header records",
        primaryKey: ["deliveryDocument"],
        columns: [
          "deliveryDocument",
          "creationDate",
          "shippingPoint",
          "overallGoodsMovementStatus",
          "overallPickingStatus",
        ],
      },
      outbound_delivery_items: {
        description: "Outbound delivery item lines",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "deliveryDocument",
          "deliveryDocumentItem",
          "plant",
          "storageLocation",
          "actualDeliveryQuantity",
          "deliveryQuantityUnit",
          "referenceSdDocument",
          "referenceSdDocumentItem",
        ],
      },
      billing_document_headers: {
        description: "Billing document headers",
        primaryKey: ["billingDocument"],
        columns: [
          "billingDocument",
          "billingDocumentType",
          "creationDate",
          "billingDocumentDate",
          "billingDocumentIsCancelled",
          "cancelledBillingDocument",
          "totalNetAmount",
          "transactionCurrency",
          "companyCode",
          "fiscalYear",
          "accountingDocument",
          "soldToParty",
        ],
      },
      billing_document_cancellations: {
        description: "Cancelled billing document records",
        primaryKey: ["billingDocument"],
        columns: [
          "billingDocument",
          "billingDocumentType",
          "creationDate",
          "billingDocumentDate",
          "billingDocumentIsCancelled",
          "cancelledBillingDocument",
          "totalNetAmount",
          "transactionCurrency",
          "companyCode",
          "fiscalYear",
          "accountingDocument",
          "soldToParty",
        ],
      },
      billing_document_items: {
        description: "Billing document items",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "billingDocument",
          "billingDocumentItem",
          "material",
          "billingQuantity",
          "billingQuantityUnit",
          "netAmount",
          "transactionCurrency",
          "referenceSdDocument",
          "referenceSdDocumentItem",
        ],
      },
      journal_entry_items_accounts_receivable: {
        description: "Accounts receivable journal entry items",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "companyCode",
          "fiscalYear",
          "accountingDocument",
          "glAccount",
          "referenceDocument",
          "transactionCurrency",
          "amountInTransactionCurrency",
          "postingDate",
          "documentDate",
          "accountingDocumentType",
          "accountingDocumentItem",
          "customer",
          "clearingDate",
          "clearingAccountingDocument",
          "clearingDocFiscalYear",
        ],
      },
      payments_accounts_receivable: {
        description: "Accounts receivable payment/clearing items",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "companyCode",
          "fiscalYear",
          "accountingDocument",
          "accountingDocumentItem",
          "clearingDate",
          "clearingAccountingDocument",
          "clearingDocFiscalYear",
          "amountInTransactionCurrency",
          "transactionCurrency",
          "customer",
        ],
      },
      business_partners: {
        description: "Business partners and customers",
        primaryKey: ["businessPartner"],
        columns: [
          "businessPartner",
          "customer",
          "businessPartnerFullName",
          "businessPartnerName",
          "businessPartnerIsBlocked",
        ],
      },
      business_partner_addresses: {
        description: "Customer address records",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "businessPartner",
          "addressId",
          "cityName",
          "country",
          "postalCode",
          "region",
          "streetName",
        ],
      },
      customer_company_assignments: {
        description: "Customer to company code assignments",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "customer",
          "companyCode",
          "paymentTerms",
          "reconciliationAccount",
          "deletionIndicator",
          "customerAccountGroup",
        ],
      },
      customer_sales_area_assignments: {
        description: "Customer sales area assignments",
        primaryKey: ["rowKey"],
        columns: [
          "rowKey",
          "customer",
          "salesOrganization",
          "distributionChannel",
          "division",
          "currency",
          "customerPaymentTerms",
          "deliveryPriority",
          "incotermsClassification",
          "incotermsLocation1",
          "shippingCondition",
        ],
      },
      products: {
        description: "Product master records",
        primaryKey: ["product"],
        columns: ["product", "productType", "productOldId", "productGroup", "baseUnit"],
      },
      product_descriptions: {
        description: "Product description records",
        primaryKey: ["rowKey"],
        columns: ["rowKey", "product", "language", "productDescription"],
      },
      plants: {
        description: "Plant master records",
        primaryKey: ["plant"],
        columns: ["plant", "plantName", "valuationArea", "customer", "supplier", "salesOrganization"],
      },
      product_plants: {
        description: "Product by plant settings",
        primaryKey: ["rowKey"],
        columns: ["rowKey", "product", "plant", "countryOfOrigin", "regionOfOrigin", "availabilityCheckType", "profitCenter", "mrpType"],
      },
      product_storage_locations: {
        description: "Product storage location assignments",
        primaryKey: ["rowKey"],
        columns: ["rowKey", "product", "plant", "storageLocation", "physicalInventoryBlockInd", "dateOfLastPostedCntUnRstrcdStk"],
      },
    },
    joins: [
      ["sales_order_headers.salesOrder", "sales_order_items.salesOrder"],
      ["sales_order_items.salesOrder", "sales_order_schedule_lines.salesOrder"],
      ["sales_order_items.salesOrderItem", "sales_order_schedule_lines.salesOrderItem"],
      ["sales_order_items.salesOrder", "outbound_delivery_items.referenceSdDocument"],
      ["sales_order_items.salesOrderItem", "outbound_delivery_items.referenceSdDocumentItem"],
      ["outbound_delivery_headers.deliveryDocument", "outbound_delivery_items.deliveryDocument"],
      ["outbound_delivery_items.deliveryDocument", "billing_document_items.referenceSdDocument"],
      ["outbound_delivery_items.deliveryDocumentItem", "billing_document_items.referenceSdDocumentItem"],
      ["billing_document_headers.billingDocument", "billing_document_items.billingDocument"],
      ["billing_document_headers.billingDocument", "billing_document_cancellations.billingDocument"],
      ["billing_document_headers.accountingDocument", "journal_entry_items_accounts_receivable.accountingDocument"],
      ["billing_document_headers.billingDocument", "journal_entry_items_accounts_receivable.referenceDocument"],
      ["journal_entry_items_accounts_receivable.clearingAccountingDocument", "payments_accounts_receivable.clearingAccountingDocument"],
      ["business_partners.businessPartner", "business_partner_addresses.businessPartner"],
      ["business_partners.customer", "customer_company_assignments.customer"],
      ["business_partners.customer", "customer_sales_area_assignments.customer"],
      ["products.product", "product_descriptions.product"],
      ["products.product", "product_plants.product"],
      ["products.product", "product_storage_locations.product"],
      ["plants.plant", "product_plants.plant"],
      ["plants.plant", "product_storage_locations.plant"],
    ],
  },
  graph: {
    labels: [
      "SalesOrder",
      "SalesOrderItem",
      "ScheduleLine",
      "Delivery",
      "DeliveryItem",
      "BillingDocument",
      "BillingCancellation",
      "BillingItem",
      "JournalEntry",
      "Payment",
      "Customer",
      "Address",
      "CustomerCompanyAssignment",
      "CustomerSalesArea",
      "Product",
      "Plant",
      "ProductPlant",
      "StorageLocation",
    ],
    relationshipTypes: [
      "PLACED_ORDER",
      "HAS_ITEM",
      "REQUESTS_PRODUCT",
      "FULFILLED_BY",
      "HAS_SCHEDULE_LINE",
      "FULFILLED_BY_DELIVERY",
      "SHIPPED_FROM",
      "RECEIVED_BILL",
      "HAS_CANCELLATION",
      "CANCELS_DOCUMENT",
      "BILLED_FROM_DELIVERY",
      "BILLS_PRODUCT",
      "POSTED_TO",
      "CLEARED_BY",
      "HAS_ADDRESS",
      "HAS_COMPANY_ASSIGNMENT",
      "HAS_SALES_AREA",
      "AVAILABLE_AT_PLANT",
      "MAPS_TO_PLANT",
      "STORED_AT",
      "BELONGS_TO_PLANT",
    ],
    nodeProperties: ["id", "kind", "label", "groupName", "refId", "payload"],
  },
};

export function schemaSummaryForPrompt() {
  const relationalSummary = Object.entries(schemaCatalog.relational.tables)
    .map(([tableName, table]) => `${tableName}(${table.columns.join(", ")})`)
    .join("\n");

  const joinSummary = schemaCatalog.relational.joins
    .map(([left, right]) => `${left} = ${right}`)
    .join("\n");

  return [
    "RELATIONAL TABLES",
    relationalSummary,
    "",
    "KNOWN JOINS",
    joinSummary,
    "",
    `GRAPH LABELS: ${schemaCatalog.graph.labels.join(", ")}`,
    `GRAPH RELATIONSHIPS: ${schemaCatalog.graph.relationshipTypes.join(", ")}`,
  ].join("\n");
}
