function numberValue(value) {
  if (value === null || value === undefined || value === "") {
    return null;
  }
  const parsed = Number(value);
  return Number.isNaN(parsed) ? null : parsed;
}

function boolValue(value) {
  return value ? 1 : 0;
}

function itemCode(value) {
  if (value === null || value === undefined || value === "") {
    return "";
  }
  const normalized = String(value).replace(/^0+/, "");
  return normalized || "0";
}

export const normalizers = {
  sales_order_headers: (record) => ({
    salesOrder: record.salesOrder,
    salesOrderType: record.salesOrderType,
    salesOrganization: record.salesOrganization,
    distributionChannel: record.distributionChannel,
    organizationDivision: record.organizationDivision,
    soldToParty: record.soldToParty,
    creationDate: record.creationDate,
    totalNetAmount: numberValue(record.totalNetAmount),
    overallDeliveryStatus: record.overallDeliveryStatus,
    overallOrdReltdBillgStatus: record.overallOrdReltdBillgStatus,
    transactionCurrency: record.transactionCurrency,
    requestedDeliveryDate: record.requestedDeliveryDate,
    customerPaymentTerms: record.customerPaymentTerms,
  }),
  sales_order_items: (record) => ({
    rowKey: `${record.salesOrder}:${itemCode(record.salesOrderItem)}`,
    salesOrder: record.salesOrder,
    salesOrderItem: itemCode(record.salesOrderItem),
    material: record.material,
    requestedQuantity: numberValue(record.requestedQuantity),
    requestedQuantityUnit: record.requestedQuantityUnit,
    netAmount: numberValue(record.netAmount),
    transactionCurrency: record.transactionCurrency,
    productionPlant: record.productionPlant,
    storageLocation: record.storageLocation,
  }),
  outbound_delivery_headers: (record) => ({
    deliveryDocument: record.deliveryDocument,
    creationDate: record.creationDate,
    shippingPoint: record.shippingPoint,
    overallGoodsMovementStatus: record.overallGoodsMovementStatus,
    overallPickingStatus: record.overallPickingStatus,
  }),
  outbound_delivery_items: (record) => ({
    rowKey: `${record.deliveryDocument}:${itemCode(record.deliveryDocumentItem)}`,
    deliveryDocument: record.deliveryDocument,
    deliveryDocumentItem: itemCode(record.deliveryDocumentItem),
    plant: record.plant,
    storageLocation: record.storageLocation,
    actualDeliveryQuantity: numberValue(record.actualDeliveryQuantity),
    deliveryQuantityUnit: record.deliveryQuantityUnit,
    referenceSdDocument: record.referenceSdDocument,
    referenceSdDocumentItem: itemCode(record.referenceSdDocumentItem),
  }),
  billing_document_headers: (record) => ({
    billingDocument: record.billingDocument,
    billingDocumentType: record.billingDocumentType,
    creationDate: record.creationDate,
    billingDocumentDate: record.billingDocumentDate,
    billingDocumentIsCancelled: boolValue(record.billingDocumentIsCancelled),
    cancelledBillingDocument: record.cancelledBillingDocument,
    totalNetAmount: numberValue(record.totalNetAmount),
    transactionCurrency: record.transactionCurrency,
    companyCode: record.companyCode,
    fiscalYear: record.fiscalYear,
    accountingDocument: record.accountingDocument,
    soldToParty: record.soldToParty,
  }),
  billing_document_cancellations: (record) => ({
    billingDocument: record.billingDocument,
    billingDocumentType: record.billingDocumentType,
    creationDate: record.creationDate,
    billingDocumentDate: record.billingDocumentDate,
    billingDocumentIsCancelled: boolValue(record.billingDocumentIsCancelled),
    cancelledBillingDocument: record.cancelledBillingDocument,
    totalNetAmount: numberValue(record.totalNetAmount),
    transactionCurrency: record.transactionCurrency,
    companyCode: record.companyCode,
    fiscalYear: record.fiscalYear,
    accountingDocument: record.accountingDocument,
    soldToParty: record.soldToParty,
  }),
  billing_document_items: (record) => ({
    rowKey: `${record.billingDocument}:${itemCode(record.billingDocumentItem)}`,
    billingDocument: record.billingDocument,
    billingDocumentItem: itemCode(record.billingDocumentItem),
    material: record.material,
    billingQuantity: numberValue(record.billingQuantity),
    billingQuantityUnit: record.billingQuantityUnit,
    netAmount: numberValue(record.netAmount),
    transactionCurrency: record.transactionCurrency,
    referenceSdDocument: record.referenceSdDocument,
    referenceSdDocumentItem: itemCode(record.referenceSdDocumentItem),
  }),
  journal_entry_items_accounts_receivable: (record) => ({
    rowKey: `${record.accountingDocument}:${record.accountingDocumentItem}:${record.referenceDocument}`,
    companyCode: record.companyCode,
    fiscalYear: record.fiscalYear,
    accountingDocument: record.accountingDocument,
    glAccount: record.glAccount,
    referenceDocument: record.referenceDocument,
    transactionCurrency: record.transactionCurrency,
    amountInTransactionCurrency: numberValue(record.amountInTransactionCurrency),
    postingDate: record.postingDate,
    documentDate: record.documentDate,
    accountingDocumentType: record.accountingDocumentType,
    accountingDocumentItem: record.accountingDocumentItem,
    customer: record.customer,
    clearingDate: record.clearingDate,
    clearingAccountingDocument: record.clearingAccountingDocument,
    clearingDocFiscalYear: record.clearingDocFiscalYear,
  }),
  payments_accounts_receivable: (record) => ({
    rowKey: `${record.accountingDocument}:${record.accountingDocumentItem}:${record.clearingAccountingDocument}`,
    companyCode: record.companyCode,
    fiscalYear: record.fiscalYear,
    accountingDocument: record.accountingDocument,
    accountingDocumentItem: record.accountingDocumentItem,
    clearingDate: record.clearingDate,
    clearingAccountingDocument: record.clearingAccountingDocument,
    clearingDocFiscalYear: record.clearingDocFiscalYear,
    amountInTransactionCurrency: numberValue(record.amountInTransactionCurrency),
    transactionCurrency: record.transactionCurrency,
    customer: record.customer,
  }),
  business_partners: (record) => ({
    businessPartner: record.businessPartner,
    customer: record.customer,
    businessPartnerFullName: record.businessPartnerFullName,
    businessPartnerName: record.businessPartnerName,
    businessPartnerIsBlocked: boolValue(record.businessPartnerIsBlocked),
  }),
  business_partner_addresses: (record) => ({
    rowKey: `${record.businessPartner}:${record.addressId}`,
    businessPartner: record.businessPartner,
    addressId: record.addressId,
    cityName: record.cityName,
    country: record.country,
    postalCode: record.postalCode,
    region: record.region,
    streetName: record.streetName,
  }),
  customer_company_assignments: (record) => ({
    rowKey: `${record.customer}:${record.companyCode}`,
    customer: record.customer,
    companyCode: record.companyCode,
    paymentTerms: record.paymentTerms,
    reconciliationAccount: record.reconciliationAccount,
    deletionIndicator: boolValue(record.deletionIndicator),
    customerAccountGroup: record.customerAccountGroup,
  }),
  customer_sales_area_assignments: (record) => ({
    rowKey: `${record.customer}:${record.salesOrganization}:${record.distributionChannel}:${record.division}`,
    customer: record.customer,
    salesOrganization: record.salesOrganization,
    distributionChannel: record.distributionChannel,
    division: record.division,
    currency: record.currency,
    customerPaymentTerms: record.customerPaymentTerms,
    deliveryPriority: record.deliveryPriority,
    incotermsClassification: record.incotermsClassification,
    incotermsLocation1: record.incotermsLocation1,
    shippingCondition: record.shippingCondition,
  }),
  products: (record) => ({
    product: record.product,
    productType: record.productType,
    productOldId: record.productOldId,
    productGroup: record.productGroup,
    baseUnit: record.baseUnit,
  }),
  product_descriptions: (record) => ({
    rowKey: `${record.product}:${record.language || "NA"}`,
    product: record.product,
    language: record.language || "",
    productDescription: record.productDescription || "",
  }),
  plants: (record) => ({
    plant: record.plant,
    plantName: record.plantName,
    valuationArea: record.valuationArea,
    customer: record.customer,
    supplier: record.supplier,
    salesOrganization: record.salesOrganization,
  }),
  product_plants: (record) => ({
    rowKey: `${record.product}:${record.plant}`,
    product: record.product,
    plant: record.plant,
    countryOfOrigin: record.countryOfOrigin,
    regionOfOrigin: record.regionOfOrigin,
    availabilityCheckType: record.availabilityCheckType,
    profitCenter: record.profitCenter,
    mrpType: record.mrpType,
  }),
  product_storage_locations: (record) => ({
    rowKey: `${record.product}:${record.plant}:${record.storageLocation}`,
    product: record.product,
    plant: record.plant,
    storageLocation: record.storageLocation,
    physicalInventoryBlockInd: record.physicalInventoryBlockInd,
    dateOfLastPostedCntUnRstrcdStk: record.dateOfLastPostedCntUnRstrcdStk,
  }),
  sales_order_schedule_lines: (record) => ({
    rowKey: `${record.salesOrder}:${itemCode(record.salesOrderItem)}:${itemCode(record.scheduleLine)}`,
    salesOrder: record.salesOrder,
    salesOrderItem: itemCode(record.salesOrderItem),
    scheduleLine: itemCode(record.scheduleLine),
    confirmedDeliveryDate: record.confirmedDeliveryDate,
    orderQuantityUnit: record.orderQuantityUnit,
    confdOrderQtyByMatlAvailCheck: numberValue(record.confdOrderQtyByMatlAvailCheck),
  }),
};
